import Foundation

/// The privacy policy body, verbatim from the provided draft (Draft v1). The draft's
/// front-matter metadata and the trailing "Open items" checklist are intentionally
/// omitted; the policy prose is kept exactly, including bracketed placeholders and
/// review notes, because it is legal text that must not be fabricated or rewritten.
enum PrivacyPolicyContent {
    static var lines: [String] { markdown.components(separatedBy: "\n") }

    static let markdown = """
**Last updated:** 1 September 2026
**Applies to:** the Keel iOS app and any associated services (together, "Keel," "we," "us")

### Who we are

Keel is built by TRY Keel Pty Ltd (ACN 701 528 467, ABN 50 701 528 467), based in Melbourne, Australia. Keel is a companion app for women navigating perimenopause. This policy explains what information we collect, why, and what you can do about it.

Keel supports and informs. It does not diagnose, prescribe, or replace your doctor. Nothing in Keel, including anything generated by its AI features, is medical advice.

### What we collect

**What you tell us directly:**
- Account information: your name (or however you choose to identify yourself), email address, and login credentials.
- Daily check-in data: mood, energy, symptoms you log, and any notes you add (typed or voice, transcribed).
- Treatment and supplement information: HRT type, dose, brand, application method, and any supplements or medications you choose to log.
- Cycle information, if you choose to track it.
- Lab results, if you choose to add them.
- Your chosen pathway (natural, medical, or blended) and any changes to it.

**What we pull in automatically, with your permission:**
- Apple Health data you authorise (read-only; Keel never writes anything back): sleep; activity such as steps, exercise minutes, active energy, flights climbed, and walking or running distance; heart and vitals such as heart rate, resting heart rate, heart rate variability, blood pressure, respiratory rate, blood oxygen, body temperature, wrist temperature, basal body temperature, and body weight; menstrual flow; mindful minutes; and any perimenopause-related symptoms you record in Health (for example hot flushes and night sweats). Keel reads only the categories you approve, and only to fold them into your own record.

**What we collect automatically:**
- Basic device and usage information needed to keep the app running and secure (app version, crash logs, general performance data). We do not use this for advertising.

We do not collect more than we need. If a feature doesn't need a piece of information to work, Keel doesn't ask for it.

### Why we collect it

- To provide the daily check-in, dashboard, and treatment logging features you're using.
- To generate the pattern observations and GP report, where you're on a plan that includes these.
- To keep your account secure and the app working properly.
- To improve Keel over time, using de-identified, aggregated information wherever possible.

We do not use your health information for advertising or marketing, and we never sell it. Full stop.

### The AI features, specifically

Some of Keel's features (pattern observations, the GP report) use AI to help generate plain-language summaries from your own data. Here's exactly how that works:

- The processing runs on your device, not on our servers. On supported devices it uses Apple's on-device intelligence. Either way, the information used stays on your phone and is not sent to us or to any other company.
- Only the minimum information needed to generate that specific summary is used.
- Any AI-generated observation is written to reflect a possible pattern in your own data, not a clinical assessment or medical opinion, and is always presented for you to review, not as an instruction.

**Automated decision-making disclosure** (required under Australian law from 10 December 2026): Keel's pattern observations and GP report content are generated using automated processing (AI) based on the health and lifestyle information you provide. These outputs are informational only. No automated process makes a decision about your health, treatment, or care on your behalf; every output is something you review, edit, and choose whether to act on or share with your doctor.

### Where your information is stored

Your information is stored on your device, and if you are signed in it syncs to your own private iCloud account using Apple's CloudKit. It lives in the private database tied to your Apple ID, which only you can reach; the Keel team cannot see into it. Apple stores and handles iCloud data on its own infrastructure, which may be located outside Australia, under Apple's iCloud terms and privacy policy.

### Who we share information with

We work with a small number of service providers to run Keel:
- **Apple** - secure storage and sync of your private data through iCloud (using Apple's CloudKit, in the private database tied to your Apple ID); the HealthKit data you authorise; and processing any subscription payment through the App Store (Apple handles payment details directly; we never see your card information).

We do not sell your information to anyone. We do not share it with advertisers. We only share what's described above, and only for the purposes described above.

If required by law, we may need to disclose information to a regulator or court. We'll tell you if this happens unless we're legally prevented from doing so.

### Sensitive information gets extra care

Some of what you log in Keel - cycle data, HRT and treatment details, symptoms - is sensitive health information under Australian privacy law, and we treat it accordingly: stored securely, access restricted to you, never used for anything beyond providing you the service.

### Your choices and rights

You can:
- See what information Keel holds about you.
- Correct anything that's wrong.
- Delete your account and data at any time, directly in the app. This removes it from your device and from your private iCloud storage.
- Ask us what's been shared and with whom.
- Turn off any AI feature at any time; the rest of Keel keeps working normally.

To exercise any of these, contact us at keel@therecalibrationyears.com.

### How long we keep your information

We keep your information for as long as your account is active, plus a short period afterwards to handle any outstanding requests or legal obligations. When you delete your account, your personal information is deleted from your device and your private iCloud storage within 30 days, except where we are required to retain something by law.

### Keeping your information secure

We use industry-standard security practices, including encryption in transit and at rest, to protect your information. No system is completely immune to risk, but we take this seriously, precisely because of what's at stake with health data. If a security incident affects your information, we'll notify you in line with our obligations under the Privacy Act.

### Changes to this policy

If we make a material change to this policy, we'll let you know before it takes effect, not just post a quiet update.

### Contact us

Questions about this policy or your information: keel@therecalibrationyears.com.
If you're not satisfied with our response, you can contact the Office of the Australian Information Commissioner (OAIC) at oaic.gov.au.
"""
}
