import Foundation

/// The privacy policy body, verbatim from the provided draft (Draft v1). The draft's
/// front-matter metadata and the trailing "Open items" checklist are intentionally
/// omitted; the policy prose is kept exactly, including bracketed placeholders and
/// review notes, because it is legal text that must not be fabricated or rewritten.
enum PrivacyPolicyContent {
    static var lines: [String] { markdown.components(separatedBy: "\n") }

    static let markdown = """
**Last updated:** [date]
**Applies to:** the Keel iOS app and any associated services (together, "Keel," "we," "us")

### Who we are

Keel is built by [TRY Keel Pty Ltd, ACN [pending] / currently Mischa Douglas trading as The Recalibration Years, ABN [ABN]], based in Melbourne, Australia. Keel is a companion app for women navigating perimenopause. This policy explains what information we collect, why, and what you can do about it.

Keel supports and informs. It does not diagnose, prescribe, or replace your doctor. Nothing in Keel, including anything generated by its AI features, is medical advice.

### What we collect

**What you tell us directly:**
- Account information: your name (or however you choose to identify yourself), email address, and login credentials.
- Daily check-in data: mood, energy, symptoms you log, and any notes you add (typed or voice, transcribed).
- Treatment and supplement information: HRT type, dose, brand, application method, and any supplements or medications you choose to log.
- Cycle information, if you choose to track it.
- Lab results, if you choose to add them.
- Your chosen pathway (natural, medical, or blended) and any changes to it.

**What we pull in automatically, with your permission:**
- Apple HealthKit data you authorise: sleep, steps, heart rate, and workouts. [Confirm final V1 integration list with Chunru before publishing.]

**What we collect automatically:**
- Basic device and usage information needed to keep the app running and secure (app version, crash logs, general performance data). We do not use this for advertising.

We do not collect more than we need. If a feature doesn't need a piece of information to work, Keel doesn't ask for it.

### Why we collect it

- To provide the daily check-in, dashboard, and treatment logging features you're using.
- To generate the pattern observations and GP report, where you're on a plan that includes these.
- To keep your account secure and the app working properly.
- To improve Keel over time, using de-identified, aggregated information wherever possible.

We do not use your health information for advertising or marketing, and we never sell it. Full stop.

### The AI features, specifically

Some of Keel's features (pattern observations, the GP report) use Anthropic's Claude API to help generate plain-language summaries from your own data. Here's exactly how that works:

- Only the minimum information needed to generate the specific output is sent. [Confirm exact scope with Chunru's system prompt / Edge Function design once finalised - this section needs to match the build precisely.]
- This processing happens through a secure server-side connection (a Supabase Edge Function); your raw data is not sent directly from your phone to a third party.
- Anthropic processes this information under its own data handling terms as our processor, not as an independent user of your data. [Confirm current Anthropic API data retention/training terms before publishing - these can change and need verifying at time of writing, not assumed from this draft.]
- Any AI-generated observation is written to reflect a possible pattern in your own data, not a clinical assessment or medical opinion, and is always presented for you to review, not as an instruction.

**Automated decision-making disclosure** (required under Australian law from 10 December 2026): Keel's pattern observations and GP report content are generated using automated processing (AI) based on the health and lifestyle information you provide. These outputs are informational only. No automated process makes a decision about your health, treatment, or care on your behalf; every output is something you review, edit, and choose whether to act on or share with your doctor.

### Where your information is stored

Your information is stored on Supabase infrastructure hosted in Sydney, Australia, with row-level security applied from the first version of the app. This means your data stays in Australia and access is restricted at the database level to your own account.

### Who we share information with

We work with a small number of service providers to run Keel:
- **Supabase** (Sydney, Australia) - hosting and database infrastructure.
- **Anthropic** - AI processing for pattern observations and the GP report, only when you use those features, and only the minimum data needed.
- **Apple** - for HealthKit data you authorise, and for processing any subscription payment through the App Store (Apple handles payment details directly; we never see your card information).
- **RevenueCat** - subscription management. [Confirm exact data RevenueCat receives with Chunru.]

We do not sell your information to anyone. We do not share it with advertisers. We only share what's described above, and only for the purposes described above.

If required by law, we may need to disclose information to a regulator or court. We'll tell you if this happens unless we're legally prevented from doing so.

### Sensitive information gets extra care

Some of what you log in Keel - cycle data, HRT and treatment details, symptoms - is sensitive health information under Australian privacy law, and we treat it accordingly: stored securely, access restricted to you, never used for anything beyond providing you the service.

[Decide with Chunru: does Keel need an equivalent to Bevel's "reproductive health data isn't sent to the AI layer unless you opt in" pattern? Worth deciding before this section is finalised, particularly for cycle data.]

### Your choices and rights

You can:
- See what information Keel holds about you.
- Correct anything that's wrong.
- Delete your account and data at any time, directly in the app. [Confirm deletion flow meets App Store requirement before publishing.]
- Ask us what's been shared and with whom.
- Turn off any AI feature at any time; the rest of Keel keeps working normally.

To exercise any of these, contact us at [support email].

### How long we keep your information

We keep your information for as long as your account is active, plus a short period afterwards to handle any outstanding requests or legal obligations. When you delete your account, your personal information is deleted [confirm exact process and timeframe with Chunru], except where we're required to retain something by law.

### Keeping your information secure

We use industry-standard security practices, including encryption in transit and at rest, to protect your information. No system is completely immune to risk, but we take this seriously, precisely because of what's at stake with health data. If a security incident affects your information, we'll notify you in line with our obligations under the Privacy Act.

### Changes to this policy

If we make a material change to this policy, we'll let you know before it takes effect, not just post a quiet update.

### Contact us

Questions about this policy or your information: [support email].
If you're not satisfied with our response, you can contact the Office of the Australian Information Commissioner (OAIC) at oaic.gov.au.
"""
}
